### ISSUE TITLE
Some pesky bugs

### ISSUE THREAD

**Issue by Vedabahu** [matijabozic/scoop-auto-installer#1]
- If we have one app from a different bucket but with the same name, re-importing it will install from main bucket. We can just do something like `scoop install $bucket/$app`. The app and corresponding bucket can be found on typing `scoop export`
- If the `backup.json` file is not present in the current directory from which the script is invoked, it should throw an error. It is simple to solve. Just add an if statement at the top which exits the script if the file is not found.

> Even I am not so good at PowerShell. I am just telling the possible solution. I would have helped you of I could.

**Comment by Vedabahu** [comment]
Can you also add a license please.

**Comment by matijabozic** [comment]
See you are not that bad at PowerShell in the end. ;)

Won't play around with this script anymore, it's just a dirty little script that does what it should.
We could go wild here with adding features but I don't see a point in that. 

If I catch some free time, will fork Scoop and add import / export modules and add all the bells and whistles there.
